apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: ai-analyze
  namespace: redops
spec:
  source:
    type: Binary
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile
  output:
    to:
      kind: ImageStreamTag
      name: ai-analyze:latest
