apiVersion: v1
data:
  alertmanager.yml: |
    global:
      resolve_timeout: 5m

    route:
      group_by: ['alertname']
      group_wait: 10s
      group_interval: 30s
      repeat_interval: 1h
      receiver: 'kafka-bridge'

    receivers:
      - name: 'kafka-bridge'
        webhook_configs:
          - url: 'http://alert-translator.redops.svc.cluster.local/translate'
            send_resolved: true
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"alertmanager.yml":"global:\n  resolve_timeout: 5m\n\nroute:\n  group_by: ['alertname']\n  group_wait: 10s\n  group_interval: 30s\n  repeat_interval: 1h\n  receiver: 'kafka-bridge'\n\nreceivers:\n  - name: 'kafka-bridge'\n    webhook_configs:\n      - url: 'http://redops-kafka-console-bridge-service.redops.svc:8080/topics/alerts-infra'\n        send_resolved: true\n"},"kind":"ConfigMap","metadata":{"annotations":{},"labels":{"app":"alertmanager"},"name":"alertmanager-config","namespace":"redops"}}
  creationTimestamp: "2025-07-17T13:56:57Z"
  labels:
    app: alertmanager
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:alertmanager.yml: {}
      f:metadata:
        f:annotations:
          .: {}
          f:kubectl.kubernetes.io/last-applied-configuration: {}
        f:labels:
          .: {}
          f:app: {}
    manager: kubectl-client-side-apply
    operation: Update
    time: "2025-07-17T21:12:27Z"
  name: alertmanager-config
  namespace: redops
  resourceVersion: "81817386"
  uid: cfe06738-898c-4d44-aa48-a4346d8d6d3f
