apiVersion: apps/v1
kind: Deployment
metadata:
  name: alert-translator
  namespace: redops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alert-translator
  template:
    metadata:
      labels:
        app: alert-translator
    spec:
      containers:
        - name: alert-translator
          image: image-registry.openshift-image-registry.svc:5000/redops/alert-translator:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
            requests:
              memory: "128Mi"
              cpu: "250m"
