apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: test-alert-rule
  namespace: redops
  labels:
    prometheus: redops
spec:
  groups:
    - name: demo-alert
      rules:
        - alert: DemoInternalTest
          expr: vector(1)
          for: 10s
          labels:
            severity: critical
          annotations:
            summary: "This is a test alert to check Kafka pipeline"
