apiVersion: v1
kind: Service
metadata:
  name: alert-translator
  namespace: redops
spec:
  selector:
    app: alert-translator
  ports:
    - protocol: TCP
      port: 8080         # 👈 Fix: match the container's exposed port
      targetPort: 8080
