apiVersion: apps/v1
kind: Deployment
metadata:
  name: userservice
  namespace: redops
  labels:
    app: userservice
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: userservice
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: userservice
    spec:
      containers:
        - name: userservice
          image: image-registry.openshift-image-registry.svc:5000/redops/userservice:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: PORT
              value: "8080"
            - name: ENABLE_TRACING
              value: "true"
            - name: TOKEN_EXPIRY_SECONDS
              value: "3600"
            - name: PRIV_KEY_PATH
              value: /keys/private.pem
            - name: PUB_KEY_PATH
              value: /keys/public.pem
            - name: ACCOUNTS_DB_URI
              value: postgresql://accounts-admin:accounts-pwd@accounts-db.redops.svc.cluster.local:5432/accounts
            - name: JWT_SECRET
              value: your-secret-value
            - name: ENABLE_CLOUD_TRACE
              value: "false"
          readinessProbe:
            httpGet:
              path: /ready
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 3
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - name: jwt-keys-vol
              mountPath: /keys
            - name: jwt-key-volume
              mountPath: /jwt-keys
              readOnly: true
      volumes:
        - name: jwt-keys-vol
          secret:
            secretName: jwt-keys
            defaultMode: 420
        - name: jwt-key-volume
          secret:
            secretName: jwt-public-key
            defaultMode: 420
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
