apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: test-alert
  namespace: redops
  labels:
    prometheus: redops  # 🟢 Required for ruleSelector to pick it up
spec:
  groups:
    - name: example.rules
      rules:
        - alert: DemoInternal
          expr: vector(1)
          for: 10s
          labels:
            severity: critical
          annotations:
            summary: "This is a test alert for end-to-end pipeline"
