apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-trigger
  namespace: redops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-trigger
  template:
    metadata:
      labels:
        app: kafka-trigger
    spec:
      containers:
        - name: kafka-trigger
          image: image-registry.openshift-image-registry.svc:5000/redops/kafka-trigger:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
