apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: ai-automation-run
  namespace: redops
spec:
  pipelineRef:
    name: ai-automation-pipeline
  params:
    - name: pod_name
      value: pod-name-placeholder
