apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-server-config
  namespace: redops
data:
  server.properties: |
    broker.id=0
    log.dirs=/tmp/kafka-logs
    num.network.threads=3
    num.io.threads=8
    socket.send.buffer.bytes=102400
    socket.receive.buffer.bytes=102400
    socket.request.max.bytes=104857600
    log.retention.hours=168
    log.segment.bytes=1073741824
    log.retention.check.interval.ms=300000
    zookeeper.connect=localhost:2181
    delete.topic.enable=true
