apiVersion: v1
kind: Service
metadata:
  name: kafka-jmx-exporter
  namespace: redops
  labels:
    app: kafka
spec:
  selector:
    strimzi.io/name: redops-kafka-kafka
  ports:
    - name: jmx
      port: 9404
      targetPort: 9404
  type: ClusterIP
