apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redops-kafka-kafka
  namespace: redops
spec:
  template:
    spec:
      containers:
        - name: kafka
          volumeMounts:
            - name: kafka-config-volume
              mountPath: /opt/kafka/config/server.properties
              subPath: server.properties
      volumes:
        - name: kafka-config-volume
          configMap:
            name: kafka-server-config
