apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"kafka.strimzi.io/v1beta2","kind":"Kafka","metadata":{"annotations":{},"name":"redops-kafka","namespace":"redops"},"spec":{"entityOperator":{"topicOperator":{},"userOperator":{}},"kafka":{"config":{"default.replication.factor":1,"inter.broker.protocol.version":"3.0","log.message.format.version":"3.0","num.partitions":1,"offsets.topic.replication.factor":1,"transaction.state.log.min.isr":1,"transaction.state.log.replication.factor":1},"listeners":[{"name":"plain","port":9092,"tls":false,"type":"internal"}],"replicas":1,"storage":{"type":"ephemeral"},"version":"3.6.0"},"zookeeper":{"replicas":1,"storage":{"type":"ephemeral"}}}}
  creationTimestamp: "2025-07-16T10:02:28Z"
  generation: 4
  managedFields:
  - apiVersion: kafka.strimzi.io/v1beta2
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:kubectl.kubernetes.io/last-applied-configuration: {}
      f:spec:
        .: {}
        f:entityOperator:
          .: {}
          f:topicOperator: {}
          f:userOperator: {}
        f:kafka:
          .: {}
          f:config:
            .: {}
            f:default.replication.factor: {}
            f:num.partitions: {}
            f:offsets.topic.replication.factor: {}
            f:transaction.state.log.min.isr: {}
            f:transaction.state.log.replication.factor: {}
          f:listeners: {}
          f:replicas: {}
          f:storage:
            .: {}
            f:type: {}
        f:zookeeper:
          .: {}
          f:replicas: {}
          f:storage:
            .: {}
            f:type: {}
    manager: kubectl-client-side-apply
    operation: Update
    time: "2025-07-18T10:01:59Z"
  - apiVersion: kafka.strimzi.io/v1beta2
    fieldsType: FieldsV1
    fieldsV1:
      f:spec:
        f:kafka:
          f:config:
            f:inter.broker.protocol.version: {}
            f:log.message.format.version: {}
          f:version: {}
    manager: kubectl-edit
    operation: Update
    time: "2025-07-18T11:23:04Z"
  - apiVersion: kafka.strimzi.io/v1beta2
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        .: {}
        f:clusterId: {}
        f:conditions: {}
        f:kafkaMetadataState: {}
        f:kafkaVersion: {}
        f:observedGeneration: {}
        f:operatorLastSuccessfulVersion: {}
        f:registeredNodeIds: {}
    manager: strimzi-cluster-operator
    operation: Update
    subresource: status
    time: "2025-07-18T11:23:04Z"
  name: redops-kafka
  namespace: redops
  resourceVersion: "84556300"
  uid: 837e0c5a-4d79-48c7-abf3-429f4457450d
spec:
  entityOperator:
    topicOperator: {}
    userOperator: {}
  kafka:
    config:
      default.replication.factor: 1
      inter.broker.protocol.version: "3.8"
      log.message.format.version: "3.8"
      num.partitions: 1
      offsets.topic.replication.factor: 1
      transaction.state.log.min.isr: 1
      transaction.state.log.replication.factor: 1
    listeners:
    - name: plain
      port: 9092
      tls: false
      type: internal
    replicas: 1
    storage:
      type: ephemeral
    version: 3.8.0
  zookeeper:
    replicas: 1
    storage:
      type: ephemeral
status:
  clusterId: uE_HZn5DQ7aj-eYmcbnQbg
  conditions:
  - lastTransitionTime: "2025-07-18T11:23:04.141064074Z"
    message: Support for ZooKeeper-based Apache Kafka clusters will be removed in the next Strimzi release (0.46.0). Please migrate to KRaft.
    reason: ZooKeeperRemoval
    status: "True"
    type: Warning
  - lastTransitionTime: "2025-07-18T11:23:04.321894157Z"
    message: log.message.format.version (3.9) and inter.broker.protocol.version (3.9) used by the brokers have to be set and be lower or equal to the Kafka broker version we downgrade to (3.8.0)
    reason: KafkaUpgradeException
    status: "True"
    type: NotReady
  kafkaMetadataState: ZooKeeper
  kafkaVersion: 3.8.0
  observedGeneration: 4
  operatorLastSuccessfulVersion: 0.45.0.redhat-00004
  registeredNodeIds:
  - 0
