apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: redops-kafka
  namespace: redops
spec:
  kafka:
    replicas: 1
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      log.message.format.version: "2.8"
    jvmOptions:
      javaOptions: "-javaagent:/opt/jmx-exporter/jmx_prometheus_javaagent.jar=5556:/etc/jmx-exporter/config.yaml"
    template:
      pod:
        volumes:
          - name: jmx-exporter
            emptyDir: {}
          - name: jmx-config
            configMap:
              name: jmx-exporter-config
        initContainers:
          - name: jmx-exporter-init
            image: image-registry.openshift-image-registry.svc:5000/redops/jmx-exporter:latest
            command: ["sh", "-c", "cp /jmx_prometheus_javaagent.jar /opt/jmx-exporter/jmx_prometheus_javaagent.jar"]
            volumeMounts:
              - name: jmx-exporter
                mountPath: /opt/jmx-exporter
        containers:
          - name: kafka
            volumeMounts:
              - name: jmx-exporter
                mountPath: /opt/jmx-exporter
              - name: jmx-config
                mountPath: /etc/jmx-exporter
    storage:
      type: ephemeral
  zookeeper:
    replicas: 1
    storage:
      type: ephemeral
  entityOperator:
    topicOperator: {}
    userOperator: {}
