apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: redops-kafka
  namespace: redops
spec:
  kafka:
    replicas: 1
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
    storage:
      type: ephemeral
  zookeeper:
    replicas: 1
    storage:
      type: ephemeral
  entityOperator:
    topicOperator: {}
    userOperator: {}
