apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: default
  namespace: redops
spec:
  description: Default project
  sourceRepos:
    - '*'
  destinations:
    - namespace: redops
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
