apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redops-demo
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: https://github.com/vignesh191024/redops-prototype.git
    targetRevision: main
    path: base
  destination:
    server: https://kubernetes.default.svc
    namespace: redops
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
