apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka-trigger
  namespace: redops
spec:
  project: default
  source:
    repoURL: 'https://github.com/vignesh191024/redops-gitops'
    targetRevision: main
    path: apps/kafka-trigger
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: redops
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
