apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: kafka-webhook-config
  namespace: redops
spec:
  route:
    receiver: kafka-receiver
  receivers:
    - name: kafka-receiver
      webhookConfigs:
        - url: http://kafka-webhook.redops.svc:80/
          sendResolved: true
