apiVersion: v1
kind: Pod
metadata:
  name: kafka-client
  namespace: redops
spec:
  containers:
  - name: kafka-client
    image: docker.io/bitnami/kafka:3.5.0
    command: [ "sleep", "infinity" ]
    securityContext:
      runAsUser: 1001
  restartPolicy: Never
