apiVersion: v1
kind: Service
metadata:
  name: alertmanager
  namespace: redops
  labels:
    app: alertmanager
spec:
  ports:
    - name: web
      port: 9093
      targetPort: 9093
  selector:
    app: alertmanager
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alertmanager
  namespace: redops
  labels:
    app: alertmanager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alertmanager
  template:
    metadata:
      labels:
        app: alertmanager
    spec:
      containers:
        - name: alertmanager
          image: quay.io/prometheus/alertmanager:v0.26.0
          args:
            - "--config.file=/etc/alertmanager/alertmanager.yml"
            - "--storage.path=/alertmanager"
          ports:
            - containerPort: 9093
          volumeMounts:
            - name: config-volume
              mountPath: /etc/alertmanager
      volumes:
        - name: config-volume
          configMap:
            name: alertmanager-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
  namespace: redops
  labels:
    app: alertmanager

data:
  alertmanager.yml: |
    global:
      resolve_timeout: 5m

    route:
      group_by: ['alertname']
      group_wait: 10s
      group_interval: 30s
      repeat_interval: 1h
      receiver: 'kafka-webhook'

    receivers:
      - name: 'kafka-webhook'
        webhook_configs:
          - url: 'http://kafka-webhook.redops.svc:80/'
            send_resolved: true
