apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: kafka.rules
  namespace: redops
  labels:
    prometheus: redops
    role: alert-rules
spec:
  groups:
    - name: kafka.rules
      rules:
        - alert: KafkaBrokerDown
          expr: absent(up{pod=~"redops-kafka-kafka-.*", namespace="redops"} == 1)
          for: 1m
          labels:
            severity: critical
          annotations:
            summary: "Kafka broker is down"
            description: "No healthy targets for Kafka broker pod redops-kafka-kafka-0 in the last 1 minute."
