apiVersion: apps/v1
kind: Deployment
metadata:
  name: accounts-api
  namespace: redops
  labels:
    app: accounts-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: accounts-api
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: accounts-api
    spec:
      containers:
        - name: accounts-api
          image: image-registry.openshift-image-registry.svc:5000/redops/accounts-api:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: ACCOUNTS_DB_URI
              value: postgresql://accounts-admin:accounts-pwd@accounts-db.redops.svc.cluster.local:5432/accounts
            - name: ENABLE_TRACING
              value: "false"
            - name: PORT
              value: "8080"
            - name: POSTGRESQL_DATABASE
              value: accounts
            - name: POSTGRESQL_PASSWORD
              value: accounts-pwd
            - name: POSTGRESQL_USER
              value: accounts-admin
            - name: ALLOW_EMPTY_PASSWORD
              value: "yes"
            - name: BITNAMI_POSTGRESQL_DATA_DIR
              value: /var/lib/postgresql/data
            - name: TOKEN_EXPIRY_SECONDS
              value: "3600"
            - name: DISABLE_AUTH
              value: "true"
            - name: DEBUG_SLEEP
              value: "1"
            - name: PRIV_KEY_PATH
              value: /app/secrets/private.pem
            - name: PUB_KEY_PATH
              value: /app/secrets/public.pem
          resources:
            limits:
              cpu: 300m
              memory: 512Mi
            requests:
              cpu: 200m
              memory: 200Mi
          volumeMounts:
            - mountPath: /app/secrets
              name: jwt-keys
      volumes:
        - name: jwt-keys
          secret:
            secretName: userservice-jwt-keys
      restartPolicy: Always
      dnsPolicy: ClusterFirst
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
