apiVersion: argoproj.io/v1beta1
kind: ArgoCD
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"argoproj.io/v1beta1","kind":"ArgoCD","metadata":{"annotations":{},"name":"redops-argocd","namespace":"redops"},"spec":{"applicationSet":{"resources":{"limits":{"cpu":"500m","memory":"256Mi"},"requests":{"cpu":"250m","memory":"128Mi"}}},"controller":{"resources":{"limits":{"cpu":"500m","memory":"512Mi"},"requests":{"cpu":"250m","memory":"256Mi"}}},"redis":{"resources":{"limits":{"cpu":"500m","memory":"256Mi"},"requests":{"cpu":"250m","memory":"128Mi"}}},"repo":{"resources":{"limits":{"cpu":"500m","memory":"256Mi"},"requests":{"cpu":"250m","memory":"128Mi"}}},"server":{"route":{"enabled":true}},"sso":{"dex":{"openShiftOAuth":true},"provider":"dex"}}}
  creationTimestamp: "2025-07-16T09:29:17Z"
  finalizers:
  - argoproj.io/finalizer
  generation: 3
  managedFields:
  - apiVersion: argoproj.io/v1beta1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:kubectl.kubernetes.io/last-applied-configuration: {}
      f:spec:
        .: {}
        f:applicationSet:
          .: {}
          f:resources:
            .: {}
            f:limits:
              .: {}
              f:cpu: {}
              f:memory: {}
            f:requests:
              .: {}
              f:cpu: {}
              f:memory: {}
        f:controller:
          .: {}
          f:resources:
            .: {}
            f:limits:
              .: {}
              f:cpu: {}
              f:memory: {}
            f:requests:
              .: {}
              f:cpu: {}
              f:memory: {}
        f:redis:
          .: {}
          f:resources:
            .: {}
            f:limits:
              .: {}
              f:cpu: {}
              f:memory: {}
            f:requests:
              .: {}
              f:cpu: {}
              f:memory: {}
        f:repo:
          .: {}
          f:resources:
            .: {}
            f:limits:
              .: {}
              f:cpu: {}
              f:memory: {}
            f:requests:
              .: {}
              f:cpu: {}
              f:memory: {}
        f:server:
          .: {}
          f:route:
            .: {}
            f:enabled: {}
        f:sso:
          .: {}
          f:dex:
            .: {}
            f:openShiftOAuth: {}
          f:provider: {}
    manager: kubectl-client-side-apply
    operation: Update
    time: "2025-07-16T09:29:17Z"
  - apiVersion: argoproj.io/v1beta1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:finalizers:
          .: {}
          v:"argoproj.io/finalizer": {}
      f:spec:
        f:applicationSet:
          f:webhookServer:
            .: {}
            f:ingress:
              .: {}
              f:enabled: {}
            f:route:
              .: {}
              f:enabled: {}
        f:controller:
          f:processors: {}
          f:sharding: {}
        f:grafana:
          .: {}
          f:enabled: {}
          f:ingress:
            .: {}
            f:enabled: {}
          f:route:
            .: {}
            f:enabled: {}
        f:ha: {}
        f:initialSSHKnownHosts: {}
        f:monitoring:
          .: {}
          f:enabled: {}
        f:notifications:
          .: {}
          f:enabled: {}
        f:prometheus:
          .: {}
          f:enabled: {}
          f:ingress:
            .: {}
            f:enabled: {}
          f:route:
            .: {}
            f:enabled: {}
        f:rbac: {}
        f:server:
          f:autoscale:
            .: {}
            f:enabled: {}
          f:grpc:
            .: {}
            f:ingress:
              .: {}
              f:enabled: {}
          f:ingress:
            .: {}
            f:enabled: {}
          f:service:
            .: {}
            f:type: {}
        f:tls:
          .: {}
          f:ca: {}
    manager: manager
    operation: Update
    time: "2025-07-16T09:29:21Z"
  - apiVersion: argoproj.io/v1beta1
    fieldsType: FieldsV1
    fieldsV1:
      f:spec:
        f:ha:
          f:enabled: {}
    manager: kubectl-patch
    operation: Update
    time: "2025-07-16T18:17:09Z"
  - apiVersion: argoproj.io/v1beta1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        .: {}
        f:applicationController: {}
        f:applicationSetController: {}
        f:conditions: {}
        f:host: {}
        f:phase: {}
        f:redis: {}
        f:repo: {}
        f:server: {}
        f:sso: {}
    manager: manager
    operation: Update
    subresource: status
    time: "2025-07-16T18:17:44Z"
  name: redops-argocd
  namespace: redops
  resourceVersion: "77501489"
  uid: 3c7e7b0d-3d8e-4df0-ac79-10c2af5500cd
spec:
  applicationSet:
    resources:
      limits:
        cpu: 500m
        memory: 256Mi
      requests:
        cpu: 250m
        memory: 128Mi
    webhookServer:
      ingress:
        enabled: false
      route:
        enabled: false
  controller:
    processors: {}
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 250m
        memory: 256Mi
    sharding: {}
  grafana:
    enabled: false
    ingress:
      enabled: false
    route:
      enabled: false
  ha:
    enabled: true
  initialSSHKnownHosts: {}
  monitoring:
    enabled: false
  notifications:
    enabled: false
  prometheus:
    enabled: false
    ingress:
      enabled: false
    route:
      enabled: false
  rbac: {}
  redis:
    resources:
      limits:
        cpu: 500m
        memory: 256Mi
      requests:
        cpu: 250m
        memory: 128Mi
  repo:
    resources:
      limits:
        cpu: 500m
        memory: 256Mi
      requests:
        cpu: 250m
        memory: 128Mi
  server:
    autoscale:
      enabled: false
    grpc:
      ingress:
        enabled: false
    ingress:
      enabled: false
    route:
      enabled: true
    service:
      type: ""
  sso:
    dex:
      openShiftOAuth: true
    provider: dex
  tls:
    ca: {}
status:
  applicationController: Pending
  applicationSetController: Running
  conditions:
  - lastTransitionTime: "2025-07-16T09:29:28Z"
    message: ""
    reason: Success
    status: "True"
    type: Reconciled
  host: redops-argocd-server-redops.redhat-hackathonplus-2025-911fe55cbc5a8a309b6378b73741f03c-0000.us-south.containers.appdomain.cloud
  phase: Pending
  redis: Pending
  repo: Running
  server: Running
  sso: Running
